# Generated by Django 4.2.7 on 2024-01-07 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import emails.models


def generate_code():
    import secrets

    random = secrets.SystemRandom()
    return random.randint(1000, 9999)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VerifyEmailLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.IntegerField(default=generate_code, editable=False),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verify_email_letter",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
