# Generated by Django 4.2.7 on 2024-01-13 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("emails", "0002_rename_sent_verifyemailletter_generated_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfirmationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generated", models.DateTimeField(auto_now=True)),
                ("code", models.IntegerField(editable=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmation_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("VE", "verify email")], default="VE", max_length=16
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="confirmationcode",
            unique_together={("user", "type")},
        ),
        migrations.DeleteModel(
            name="VerifyEmailLetter",
        ),
    ]
