# Generated by Django 4.2.7 on 2024-01-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0003_confirmationcode_delete_verifyemailletter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="confirmationcode",
            name="type",
            field=models.CharField(choices=[("VE", "verify email")], max_length=16),
        ),
    ]
