# Generated by Django 4.2.7 on 2024-01-18 12:45

from django.db import migrations, models


def change_users_to_profiles(apps, schema_editor):
    Place = apps.get_model("places", "Place")
    db_alias = schema_editor.connection.alias
    for obj in Place.objects.using(db_alias).all():
        if hasattr(obj.user, "profile"):
            obj.profile = obj.user.profile
            obj.save()
        else:
            obj.delete()


def change_profiles_to_users(apps, schema_editor):
    Place = apps.get_model("places", "Place")
    db_alias = schema_editor.connection.alias
    Place.objects.using(db_alias).all().update(
        user=models.Subquery(
            Place.objects.filter(pk=models.OuterRef("pk")).values("profile__user")[:1]
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0002_place_profile"),
    ]

    operations = [
        migrations.RunPython(change_users_to_profiles, change_profiles_to_users)
    ]
