# Generated by Django 4.2.7 on 2024-01-23 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_profile_picture"),
        ("places", "0003_auto_20240118_1445"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="user",
        ),
        migrations.AlterField(
            model_name="place",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profiles.profile"
            ),
        ),
    ]
