# Generated by Django 4.2.7 on 2024-01-09 13:39

from django.db import migrations

from users.models import User
from profiles.models import Profile


def copy_users_data(apps, schema_editor):
    users = User.objects.all()
    profiles = []
    for user in users:
        profiles.append(Profile(user=user, name=user.name))
    Profile.objects.bulk_create(profiles)


def delete_models(apps, schema_editor):
    Profile.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
        ("users", "0002_user_is_email_verified"),
    ]

    operations = [
        migrations.RunPython(copy_users_data, delete_models),
    ]
