# Generated by Django 4.2.7 on 2024-01-16 18:48

from django.db import migrations, models
import profiles.validators


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_auto_20240109_1539"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="picture",
            field=models.ImageField(
                default="files/defaults/profiles_picture",
                upload_to="profiles/",
                validators=[profiles.validators.ImageRatioValidator(1, 1)],
            ),
        ),
    ]
