# Generated by Django 4.2.7 on 2024-01-25 10:20

from django.db import migrations, models
import profiles.validators


old_default_picture = "files/defaults/profiles_picture"
new_default_picture = "defaults/profiles_picture.png"


def fix_default_path(apps, schema_editor):
    Profile = apps.get_model("profiles", "Profile")
    db_alias = schema_editor.connection.alias
    for obj in Profile.objects.all():
        if obj.picture.name == old_default_picture:
            obj.picture.name = new_default_picture
            obj.save()


def unfix_default_path(apps, schema_editor):
    Profile = apps.get_model("profiles", "Profile")
    db_alias = schema_editor.connection.alias
    for obj in Profile.objects.all():
        if obj.picture.name == new_default_picture:
            obj.picture.name = old_default_picture
            obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="picture",
            field=models.ImageField(
                default="defaults\\profiles_picture.png",
                upload_to="profiles/",
                validators=[profiles.validators.ImageRatioValidator(1, 1)],
            ),
        ),
        migrations.RunPython(fix_default_path, unfix_default_path),
    ]
