# Generated by Django 4.2.7 on 2024-01-09 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_is_email_verified"),
        ("profiles", "0002_auto_20240109_1539"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
    ]
