# Generated by Django 4.2.7 on 2024-01-27 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("places", "0005_alter_place_location"),
        ("profiles", "0004_fix_defaults"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("datetime", models.DateTimeField()),
                ("price", models.DecimalField(decimal_places=4, max_digits=19)),
                ("created", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated", models.DateTimeField(auto_now=True, editable=False)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="places.place"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profile",
                    ),
                ),
            ],
        ),
    ]
