repos:
  - repo: local
    hooks:
      - id: tests
        name: run tests
        entry: python manage.py test
        language: system
        pass_filenames: false
        args: ["--settings=near.settings_test"]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.12.1
    hooks:
      - id: black
