# Generated by Django 4.2.7 on 2023-12-02 15:27

from django.db import migrations, models
import media.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="media/",
                        validators=[
                            media.validators.MimeTypeValidator(
                                allowed=[
                                    "image/jpeg",
                                    "image/png",
                                    "video/mp4",
                                    "video/mpeg",
                                ]
                            )
                        ],
                    ),
                ),
            ],
        ),
    ]
