# Generated by Django 4.2.7 on 2024-01-27 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("media", "0003_alter_media_content_type_alter_media_object_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(("app_label", "places"), ("model", "place")),
                    models.Q(("app_label", "events"), ("model", "event")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
