# Generated by Django 4.2.7 on 2024-01-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0004_alter_media_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
