# Generated by Django 4.2.7 on 2024-01-29 17:30

from django.db import migrations
import operator
import itertools


def order_randomly(apps, schema_editor):
    Media = apps.get_model("media", "Media")
    db_alias = schema_editor.connection.alias
    media = Media.objects.using(db_alias).order_by("content_type", "object_id")
    group_key = operator.attrgetter("content_type", "object_id")
    groups = {key: list(group) for key, group in itertools.groupby(media, group_key)}
    for group in groups.values():
        for i, model in enumerate(group, 1):
            model.order = i
        Media.objects.bulk_update(group, ["order"])


def set_default_order(apps, schema_editor):
    Media = apps.get_model("media", "Media")
    db_alias = schema_editor.connection.alias
    Media.objects.using(db_alias).all().update(order=1)


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0005_media_order"),
    ]

    operations = [migrations.RunPython(order_randomly, set_default_order)]
