# Generated by Django 4.2.7 on 2024-01-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("media", "0006_auto_20240129_1930"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="order",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="media",
            unique_together={("content_type", "object_id", "order")},
        ),
    ]
